Linaro/lava-test-plans

- README.md
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> README: document installation process

- README.md
- master.jinja2
- submit_for_testing.py
- variables.ini
> Add support for tags in templates

- lkft-fastboot.jinja2
> lkft-fastboot: update kir tag

- submit_for_testing.py
> submit_for_testing: allow multiple test plans in one call

- testplans/lkft-ltp/ltp-containers.yaml
- testplans/lkft-ltp/ltp-cve.yaml
- testplans/lkft-ltp/ltp-fs.yaml
- testplans/lkft-ltp/ltp-hugetlb-mm.yaml
- testplans/lkft-ltp/ltp-io-dio.yaml
- testplans/lkft-ltp/ltp-ipc.yaml
- testplans/lkft-ltp/ltp-math.yaml
- testplans/lkft-ltp/ltp-sched.yaml
- testplans/lkft-ltp/ltp-short-runs.yaml
- testplans/lkft-ltp/ltp-syscalls.yaml
- testplans/lkft-ltp/ltp-timers.yaml
> testplans: add a lkft-ltp testplan

- devices/nxp-ls2088
> devices: nxp-ls2088: add extra_kernel_args

- testcases/armnn.yaml
Dependant on https://review.linaro.org/c/ci/job/configs/+/34361/2
> armnn-ci-build: Updating build directory locations. 

- testcases/master/template-ltp.yaml.jinja2
> testcases: template-ltp: add LAVA_TEST_NAME_SUFFIX to the test_name

- testplans/armnn-benchmarking/armnn-benchmarking.yaml
adding armnn-benchmarking.yaml for benchmark testing
> Creating armnn-benchmarking.yaml

- projects/lkft/fastboot.jinja2
> project: lkft: fastboot: update kir tag

- devices/nxp-ls2088
> devices: nxp-ls2088: make DEPLOY_OS overridable

- master.jinja2
- projects/lkft/qemu.jinja2
> LKFT: LAVA job templates fixes

- testcases/ltp-controllers.yaml
- testplans/lkft-full/ltp-controllers.yaml
- testplans/lkft-ltp/ltp-controllers.yaml
> LKFT: Adding LTP controllers sub test suite

- testcases/master/template-kselftest.yaml.jinja2
- testcases/master/template-ltp.yaml.jinja2
> fix default SKIPGEN_KERNEL_VERSION

- testcases/igt-gpu-tools.yaml
IGT GPU Tools is a collection of tools for development and testing of
the DRM drivers. Adding igt-gpu-tools testcases for LKFT test plan.
> testcases: add a new test igt-gpu-tools

- testcases/master/template-kvm-unit-tests.yaml.jinja2
LKFT: KVM: update kvm-unit-tests repo link and sha
> LKFT: KVM: update kvm-unit-tests repo link and sha

- testcases/ltp-tracing.yaml
- testplans/lkft-full/ltp-tracing.yaml
- testplans/lkft-ltp/ltp-tracing.yaml
> LKFT: Adding LTP tracing sub test suite

- .gitlab-ci.yml
- README.md
- submit_for_testing.py
> README: update with docker instructions

- submit_for_testing.py
New version of black introduced one warning that is fixed in this patch.
> submit_for_testing: fix black formatting

- Dockerfile
> Dockerfile: add a file instead of cluttering in /etc/

- testcases/rteval.yaml
> testcases: add rteval

- testcases/kunit.yaml
Its a test suite within the kernel.
> testcases: add kunit

- testcases/ltp-smoketest.yaml
LTP new release 20200930 introduced smoketest. 
ref:
https://github.com/linux-test-project/ltp/commit/0d732deeb7d3b0ed4bca06696738ad0678486742
> testcases: add ltp-smoketest

- testcases/rteval.yaml
> testcases: rteval: make it possible to override test duration

- testcases/ltp-open-posix.yaml
> testcases: ltp-open-posix: extend template-master

- testcases/fwts.yaml
> testcases: add fwts suite

- testcases/master/template-ssuite.yaml.jinja2
> testcases: ssuite: fix path variable to testdir

- .travis.yml
- devices/stm32mp157c-dk2
- include/boot_target/transfer_overlay.jinja2
- projects/armnn/qemu.jinja2
- projects/armnn/variables.yaml
- qemu.jinja2
> devices: add stm32mp157c-dk2

- submit_for_testing.py
> submit_for_testing: make all default paths relative to script

- fastboot.jinja2
- include/fastboot.jinja2
- projects/lkft/fastboot.jinja2
Error response from daemon: toomanyrequests: You have reached your pull
rate limit. You may increase the limit by authenticating and upgrading:
https://www.docker.com/increase-rate-limit
Suggested-by: Milosz Wasilewski <milosz.wasilewski@linaro.org>
> docker: add local true

- testcases/ml-bench.yaml
- testplans/ml-bench/ml-bench.yaml
for ml benchmark test deployment to lava.
Signed-off-by: Theodore Grey <theodore.grey@linaro.org>
> ml-bench: adding testplans/ml-bench and testcases/ml-bench

- testcases/rcutorture.yaml
> testcases: add rcutorture

- submit_for_testing.py
Python 3.9 changes the behaviour of __file__ variable. It becomes
absolute path. This patch changes all internal paths to absolute to
accomodate this change
> submit_for_testing: use absolute paths

- .travis.yml
- testcases/pyarmnn-bench.yaml
- testplans/armnn-benchmarking/pyarmnn-bench.yaml
Commit for PyArmNN Benchmarks.
testcases: added pyarmnn-bench.yaml
testplans: added armnn-benchmark/pyarmnn-bench.yaml
> Pyarmnn bench

- testcases/kernel-smoke.yaml
> testcases/kernel-smoke.yaml: Add pm-qa test

- testcases/master/template-sysbench.yaml.jinja2
- testcases/sysbench-cpu.yaml
> testcases: add sysbench

- testcases/kernel-desktop.yaml
Recently mesa changed the name of the skip list so allow to specify from
outside and set new default value.
https://gitlab.freedesktop.org/mesa/mesa/-/commit/9cc1f089196f2f5c695dbf5f42b947b9970b8965
> testcases/kernel-desktop.yaml: Allow to specify exclude list

- testcases/kernel-benchmark.yaml
- testplans/lt-qcom/kernel/kernel-benchmark.yaml
> testplans/lt-qcom: Add kernel-benchmark testplan

- .github/workflows/test-plans-pipeline.yml
- devices/dragonboard-410c
- devices/dragonboard-820c
- devices/qcs404-evb-1k
- devices/qcs404-evb-4k
- devices/sdm845-mtp
- devices/sm8150-mtp
- devices/sm8250-mtp
- devices/sm8350-mtp
- projects/lt-qcom/devices/sm8150-mtp
- projects/lt-qcom/devices/sm8250-mtp
- projects/lt-qcom/devices/sm8350-mtp
> devices: Add qcom sm8{1,2,3}50-mtp devices

- projects/lkft/include/lkft-metadata.jinja2
Harmonize the fields names between the build and test.
> projects: lkft: metadata: harmonize fields

- projects/lkft/include/metadata.jinja2
Update to KERNEL_REPO_URL from KERNEL_REPO.
> projects: lkft: metadata: update to KERNEL_REPO_URL

- Dockerfile
> dockerfile: fix issues with ruamel.yaml

- README.md
> README: add a description of lava-test-plans

- submit_for_testing.py
Rework so the python script submit_for_testing.py uses python and not sh.
> submit_for_testing: fix, python in the py-script

- Dockerfile.ci-debian
- Dockerfile.ci-fedora
> Dockerfile.ci-*: upgrade tuxpkg to 0.9.0

- README.md
> README: installation: update readme

- lava_test_plans/devices/dragonboard-845c
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/projects/lkft-android/devices/dragonboard-845c
- lava_test_plans/projects/lkft-android/fastboot.jinja2
- lava_test_plans/projects/lkft-android/variables.ini
with some changes on the common file.
> lkft-android: add support for the db845c device

- lava_test_plans/__main__.py
If path not absolute add script_dirname to the path.
> main: add script_dirname to test*_path variable

- lava_test_plans/__main__.py
- lava_test_plans/projects/lkft/devices/variables/x15.yaml
- lava_test_plans/utils.py
- test/test_lava_test_plans.py
- test/test_validate_variables.py
- test/variables-invalid.yaml
- test/variables-valid.ini
It validates the device specific mandatory variables that are required to generate a valid LAVA job.
> validate-variables: Implementation to validate mandatory variables

- lava_test_plans/testcases/android-benchmarks-benchmarkpi.yaml
- lava_test_plans/testcases/master/template-android-benchmarks.yaml.jinja2
as one example of the benchmark testcases
> testcases: add android benchmarkpi test

- lava_test_plans/testcases/master/template-kvm-unit-tests.yaml.jinja2
> testcases: template-kvm-unit-tests: fix extra_kernel_args

- lava_test_plans/testcases/android-benchmarks-andebenchpro2015.yaml
- lava_test_plans/testcases/android-benchmarks-antutu6.yaml
- lava_test_plans/testcases/android-benchmarks-caffeinemark.yaml
- lava_test_plans/testcases/android-benchmarks-cf-bench.yaml
- lava_test_plans/testcases/android-benchmarks-gearses2eclair.yaml
- lava_test_plans/testcases/android-benchmarks-geekbench4.yaml
- lava_test_plans/testcases/android-benchmarks-glbenchmark25.yaml
- lava_test_plans/testcases/android-benchmarks-javawhetstone.yaml
- lava_test_plans/testcases/android-benchmarks-jbench.yaml
- lava_test_plans/testcases/android-benchmarks-linpack.yaml
- lava_test_plans/testcases/android-benchmarks-quadrantpro.yaml
- lava_test_plans/testcases/android-benchmarks-rl-sqlite.yaml
- lava_test_plans/testcases/android-benchmarks-scimark.yaml
- lava_test_plans/testcases/android-benchmarks-vellamo3.yaml
with the android-benchmarks-benchmarkpi.yaml testcase as reference
> testcases: add more android benchmarks

- lava_test_plans/projects/lkft-android/include/lkft-common-actions.jinja2
This is needed to fix the unknown result for boot in TuxSuite
> Rename android-boot test to boot

- lava_test_plans/include/boot_target/boot_target.jinja2
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/nfs.jinja2
fix lava job validation warnings
> Job validation fixes

- lava_test_plans/__main__.py
Black are a bit more stricked with black version 24.1.1. Black didn't complain with version 23.12.1.
> __main__: fix black-24.1.1 warning

- lava_test_plans/testcases/kselftest-short-run-4.yaml
- lava_test_plans/testcases/kselftest-short-run-7.yaml
Move secomp from kselftest-short-run-7 to short-run-4.
> testcase: kselftest: move seccomp

- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/nfs.jinja2
- lava_test_plans/qemu.jinja2
make it possible to specify MODULES_PATH the same way as we can do that in tuxrun to change where to overlay the modules.
> Modules path

- lava_test_plans/projects/lkft/fastboot.jinja2
This is needed for getting x15 boots to work.
> projects: lkft: fastboot: kir: update tag to 20240606
