- devices/juno-r2
> devices/juno-r2: fix kernel image type

- submit_for_testing.py
It might be convenient to store variables in multiple files instead of
one big file. So let --variables takes more than 1 file, and process
them *in order* so that if the same variable is defined in multiple
files the last value wins.
For example it allows to keep a generic file used by every project,
and then each project (Schneider, QCOM) can maintain their own file
with their custom variables , or overrides.
Signed-off-by: Nicolas Dechesne <nicolas.dechesne@linaro.org>
> submit_for_testing: add support for multiple variables ini file

- devices/juno-r2
- devices/x86
Some device+test combinations are causing issues with YAML rendering.
Separating disk mounting section into separate test block solves this
problem for juno and x86
> devices: move disk mounting section to separate 'test'

- devices/juno-r2
LAVA complains about the recovery namespace like this:
Job error: Unable to reuse connection from namespace 'recovery'
Rework not to use it.
Reported-by: Daniel Díaz <daniel.diaz@linaro.org>
> lkft: lava: devices: juno: remove namespace recovery

- submit_for_testing.py
Checking generated jobs with LAVA container was not working properly.
Paths and file names passed to container were incorrect and LAVA schema
checker ignored it. This patch fixes the file paths and makes LAVA
schema validator work again.
> dry-run: fix file paths passed to LAVA container

- devices/rzn1d
- devices/soca9
When booting to bootloader u-boot commands and login prompts should not
be included in the boot action.
> devices: fix boot to bootloader in rzn1d and soca9

- devices/juno-r2
- devices/nxp-ls2088
- devices/x86
- lkft-fastboot.jinja2
- lkft.jinja2
- testcases/master/template-kselftest.yaml.jinja2
- testcases/master/template-kvm-unit-tests.yaml.jinja2
Job 'context' was omited in some cases and context variables landed in
'timeouts' section. This patch adds new block where all context
variables should be defined. Also use_context variable should be set to
true in order to activate the block.
Reported-by: Michal Simek <monstr@monstr.eu>
> master: fix indentation of job context

- fastboot.jinja2
Install `android-tools-fsutils` in order to provide `img2simg` and `simg2img`. The current list of packages is invalid:
```
[...]
E: Unable to locate package img2simg
E: Unable to locate package simg2img
Unable to install using apt-get in lxc container
```
> fastboot: Fix packages for Android img tools

- README.md
- devices/qemu_arm
- devices/qemu_arm64
- devices/qemu_i386
- devices/qemu_x86_64
- fastboot.jinja2
- variables.ini
For hikey the boot.img is used for uefi, the kernel, dtb and modules can
be squashed into a generic rootfs.
> fastboot: make it possible to have boot and kernel

- submit_for_testing.py
If an unknown argument is given to submit_for_testing it should bail immediately instead of making the user believe that it cares about their feelings and arguments.
> submit_for_testing: Disallow unknown arguments

- submit_for_testing.py
It's a more general case of having git-describe instead of build numbers in QA Reports as the build ID. It is up to the user to name their builds with whatever scheme suites them, so this allows them to user a build number, a git-describe, a patronymic, or a random name.
> submit_for_testing: Rename --build-number to --build-id

- testcases/u-boot.yaml
Empty commands are no longer supported by LAVA
> u-boot: remove empty commands

- testplans/lkft-full/kselftests-native.yaml
- testplans/lkft-full/kselftests-none.yaml
- testplans/lkft-full/kselftests.yaml
Remove kselftests since in LKFT 2.0 there's no way to build or run
kselftests.
> testplans: lkft-full: remove kselftests

- submit_for_testing.py
This patch removes mutual exclusion limitation for test-plan and test-case
options. This means that one can add test cases to test-plan using
command line.
> submit_for_testing: allow test-plan + test-case

- testplans/lkft-full/ltp-open-posix.yaml
ltp-open-posix takes too long to run, so it should only be runned on
x86, i386, x15 and juno.
> testplans: lkft-full: remove ltp-open-posix

- testplans/lkft-full/ltp-short-runs.yaml
This is a compilation of short LTP tests suites, including:
* cap_bounds
* cpuhotplug
* fcntl-locktests
* filecaps
* fs_bind
* fs_perms_simple
* fsx
* nptl
* pty
* securebits
> testplans: lkft-full: Add LTP short runs

- devices/qcs404-evb-1k
- devices/qcs404-evb-4k
- devices/sdm845-mtp
- fastboot.jinja2
- projects/lkft/fastboot.jinja2
- projects/lt-qcom/fastboot.jinja2
Simplify the fastboot.jinja2 by moving the extra packages that different
project need to install into the project specific fastboot.jinja2 file.
Remove the install_packages flag and use a block lxc_extra_packages
instead. Let the different project declare the package list they need.
> fastboot: move package-list to projects

- testcases/ltp-syscalls-kasan.yaml
Remove the ltp-syscalls-kasan testcase, since we can change the
LAVA_TEST_NAME_SUFFIX via variables.ini now.
> testcases: delete ltp-syscalls-kasan

- testcases/armnn-benchmarking.yaml
armnn-ci-build: Creating armnn-benchmarking.yaml to run armnn mlperf benchmarking on debian devices.
> Creating armnn-benchmarking.yaml

- testcases/ltp-short-runs.yaml
Adding LTP sub test plan crypto as short run.
LTP crypto tested on arm64, arm and x86_64 and test takes
less than a minute to complete the run. so adding it to
ltp short run list.
> LTP: Adding sub test plan crypto

- testcases/ltp-cve.yaml
It's not a test as such, but more of an informational status of the machine on which the script runs.
Feedback from the community has been negative, so it's been decided it should be gone.
> ltp-cve: Remove spectre-meltdown-checker

- fastboot.jinja2
- nfs.jinja2
- qemu.jinja2
When trying to add OVERLAY_MODULES_* to a qemu job I see the following
LAVA JobError was printed:
case: job
case_id: 277150630
definition: lava
error_msg: Invalid deploy action: 'url' is missing for 'overlays'
error_type: Job
result: fail
Rework to add the correct indentation.
Fixes: 799b33bf141f ("add support for rootfs overlay modules")
> overlay_modules_*: fix indentation

- testcases/armnn-benchmarking.yaml
armnn-ci-benchmarking: fixing invalid test name error.
> Updating armnn-benchmarking.yaml

- projects/lkft/devices/i386
> lkft: devices: i386: add BOOT_OS_PROMPT

- testcases/ltp-short-runs-1.yaml
- testcases/ltp-short-runs-2.yaml
- testcases/ltp-short-runs-3.yaml
- testcases/ltp-short-runs.yaml
- testplans/lkft-full/ltp-short-runs-1.yaml
- testplans/lkft-full/ltp-short-runs-2.yaml
- testplans/lkft-full/ltp-short-runs-3.yaml
- testplans/lkft-full/ltp-short-runs.yaml
- testplans/lkft-ltp/ltp-short-runs-1.yaml
- testplans/lkft-ltp/ltp-short-runs-2.yaml
- testplans/lkft-ltp/ltp-short-runs-3.yaml
- testplans/lkft-ltp/ltp-short-runs.yaml
LTP short run is design to run short run test cases from a single test job
but this is cause a problem when applying overlay on qemu and x15
and causing no space left on the device.
Spliting short runs into three groups solves this problem.
Reference link to problematic lava job runs,
https://lkft.validation.linaro.org/scheduler/job/1391178
> LTP: split ltp short runs into three groups

- testplans/lkft-full/kvm-unit-tests.yaml
Remove kvm-unit-tests from all boards since we don't want to run
kvm-unit-tests on qemu "boards".
> testplans: lkft-full: remove kvm-unit-tests

- fastboot.jinja2
on LXC connected devices reboot devices to bootloader is
set to true and which is causing finalize timeout because
the device is already poweroff by that time.
Setting reboot_to_fastboot: false
Error logs before this patch,
finalize timed out after 29 seconds
finalize timed out after 1587143579 seconds
finalize timed out after 29 seconds
finalize timed out after 30 seconds
Test jobs after applying this patch works.
lava-lxc protocol: device not rebooting to fastboot
https://lkft.validation.linaro.org/scheduler/job/1426891/definition#defline1
https://lkft.validation.linaro.org/scheduler/job/1426887/definition#defline1
> LKFT: LAVA: Adding reboot_to_fastboot: false

- devices/x15
When booting X15 board with non-android build it is required to provide
proper partition number to u-boot boot command. Fortunately u-boot
allows to query partition number with partition name - 'part number'
command. This patch adds 'part number' command to X15 boot sequence.
> devices: use part number to determine partition layout

- devices/x15
As of 5/20, X15 devices have a new U-boot and partition table which allow us to use this larger partition. This way, the same X15 boards can be shared between OE and Android.
Related: https://projects.linaro.org/browse/LSS-1312
> devices: x15: Use super partition instead of userdata

- testcases/master/template-kvm-unit-tests.yaml.jinja2
kvm-unit-tests version update to latest test sources by changing
GIT_REF commit id.
Tested on x86_64 and Juno devices.
https://lkft.validation.linaro.org/results/1504975
https://lkft.validation.linaro.org/results/1506165
> LKFT: KVM: Bump GIT_REF to latest commit id

- testcases/armnn.yaml
This will allow the ArmNN UnitTests to be run on 64bit and 32bit boards.
Signed-off-by: Theodore Grey <theodore.grey@linaro.org>
> testcases: armnn: use test-definitions repo instead of inline

- projects/lkft/devices/juno-r2
The kernel Image needs bigger so the dtb wont overwrite the
kernel.
> lkft: devices: juno-r2: growing kernel image

- Dockerfile
Introduce a version string so its easy to detect when running the
container.
$ cat /lava-test-plans/.git_describe
> Dockerfile: include a .git_describe file

- Dockerfile
This is two small packages that are useful to download and query json
files.
> Dockerfile: add curl and jq packages

- submit_for_testing.py
This patch allows to use --test-case multiple times. The result is
identical as if all tests were listed together. The following will give
identical results:
--test-case test1.yaml test2.yaml test3.yaml
--test-case test1.yaml test2.yaml --test-case test3.yaml
> submit_for_testing: allow multiple --test-case params

- Dockerfile
By adding the flag to remove cache dirs makes the container smaller.
> Dockerfile: remove cache dir

- testcases/u-boot.yaml
This patch makes sure that the version string is a string. When using
2020.10 LAVA considers it a float which is not allowed.
> testcases: fix u-boot version string

- testcases/armnn-benchmarking.yaml
- testcases/armnn.yaml
- testcases/bt.yaml
- testcases/desktop.yaml
- testcases/gst-validate.yaml
- testcases/igt-gpu-tools.yaml
- testcases/kernel-bootrr.yaml
- testcases/kernel-functional-full.yaml
- testcases/kernel-functional.yaml
- testcases/kunit.yaml
- testcases/libgpiod.yaml
- testcases/libhugetlbfs.yaml
- testcases/ltp-open-posix.yaml
- testcases/master/template-kvm-unit-tests.yaml.jinja2
- testcases/master/template-master.jinja2
- testcases/master/template-network-basic-tests.yaml.jinja2
- testcases/master/template-ssuite.yaml.jinja2
- testcases/master/template-test.jinja2
- testcases/perf.yaml
- testcases/pmwg.yaml
- testcases/ptest.yaml
- testcases/rteval.yaml
- testcases/stress.yaml
- testcases/u-boot.yaml
- testcases/v4l2-compliance.yaml
- testcases/wifi.yaml
There's been too much of the same code in a lot of the tests.
so added a master/template-test file with:
{% block test_target %}
{{ super() }}
- repository: {{ TEST_DEFINITIONS_REPOSITORY }}
from: git
path: '{{test_path_file}}'
name: {% if test_plan_name is undefined %}'{{test_name}}'{% else %} '{{test_plan_name}}'{% endif %}
{% endblock test_target %}
and then the metadata block was moved into master/template-master.
the next big change was to make it possible to override the test_name variable.
> testcases: add a new master/template-test file

- testcases/ltp-open-posix.yaml
Exteded with ltp-open-posix with template-master when it should have
been extended with template-test.
Fixes: 8e27a6c701ab ("testcases: ltp-open-posix: extend template-master")
> testcases: ltp-open-posix: fix extends bug

- testcases/ltp-cve.yaml
- testcases/master/template-kselftest.yaml.jinja2
- testcases/master/template-ltp.yaml.jinja2
kselftest sources updated to stable 5.9 and this comes with new test cases
which need 30 minutes more run time. so increasing the timeout to 85 minutes.
> testcases: kselftest timeout increased to 85 minutes

- fastboot.jinja2
- include/fastboot.jinja2
- projects/lkft/fastboot.jinja2
No need to set 'local: true' anymore, solved the rate limit issue.
If the 'local: true' there will be problem with new dispatches that
doesn't have the docker image cached locally.
> docker: remove 'local: true'

- projects/lkft/fastboot.jinja2
- projects/lt-qcom/fastboot.jinja2
We now publish the kir docker image on the Linaro dockerhub account. So
we should pull from there.
Signed-off-by: Benjamin Copeland <ben.copeland@linaro.org>
> Docker: move to Linaro based kir image

- projects/lkft/devices/dragonboard-845c
- projects/lkft/fastboot.jinja2
db845c don't need the boot image to be passed in, since that gets
created in docker (kir) Image.gz+dtb.
> lkft: devices: db845: set BOOT_LABEL to kernel

- README.md
Updating our README to use GitHub workflow status, instead of TravisCI
as this is no longer used.
Signed-off-by: Benjamin Copeland <ben.copeland@linaro.org>
> README: Use GitHub actions workflow status badge

- projects/lkft/devices/qemu_arm64
Running on host arm64, running qemu_arm guest with QEMU version
'qemu-system-arm/stable,stable,now 1:3.1+dfsg-8+deb10u8 arm64' with
'virt,accel=kvm' the kernel doesn't boot with failure 'VFS: Cannot open
root device \"vda\" or unknown-block(0,0): error -6'.
Reenable qemu_arm to use 'virt-2.10,accel=kvm' to get it to boot.
> lkft: devices: qemu_arm64: set qemu_arm virt to 2.10

- projects/lt-qcom/devices/dragonboard-410c
Now camss is supported in mainline so update VIDEO_DEVICES to have camss
+ venus v4l2 devices.
> projects/lt-qcom: dragonboard-410c update VIDEO_DEVICES

- devices/qemu_arm64
- devices/qemu_i386
- devices/qemu_x86_64
- nfs.jinja2
- projects/lkft/devices/qemu_arm64
- projects/lkft/devices/qemu_i386
- projects/lkft/devices/qemu_x86_64
- qemu.jinja2
- testcases/kselftests-bpf.yaml
- testcases/kselftests-intel-x86.yaml
- testcases/kselftests-kvm.yaml
- testcases/kselftests-lkdtm.yaml
- testcases/kselftests-native.yaml
- testcases/kselftests-net.yaml
- testcases/kselftests-none.yaml
- testcases/kselftests-short-run-1.yaml
- testcases/kselftests-short-run-2.yaml
- testcases/kselftests-short-run-3.yaml
- testcases/kselftests-short-run-4.yaml
- testcases/kselftests-short-run-5.yaml
- testcases/kselftests.yaml
- testcases/master/template-kselftest.yaml.jinja2
- testplans/lkft-kselftest/kselftests-kvm.yaml
- testplans/lkft-kselftest/kselftests-lkdtm.yaml
- testplans/lkft-kselftest/kselftests-net.yaml
- testplans/lkft-kselftest/kselftests-short-run-1.yaml
- testplans/lkft-kselftest/kselftests-short-run-2.yaml
- testplans/lkft-kselftest/kselftests-short-run-3.yaml
- testplans/lkft-kselftest/kselftests-short-run-4.yaml
- testplans/lkft-kselftest/kselftests-short-run-5.yaml
Add different testcases for kselftest.
This makes it quicker to run kselftest when you can run different jobs
on different machines at the same time.
> testcases: split up kselftest in different jobs

- submit_for_testing.py
When submitting with a bad squad token the return code was 403 but the
script did not error out. The output looked like this:
[_submit_to_squad() ] Submit to https://qa-reports.linaro.org/api/submitjob/lkft/linux-next-master-sanity/next-20210322/i386
[_submit_to_squad() ] 403
[_submit_to_squad() ] {"detail": "User needs permission to submit test jobs."}
Rework so that the response raises an exception on a bad http status
code.
Suggested-by: Anders Roxell <anders.roxell@linaro.org>
Signed-off-by: Justin Cook <justin.cook@linaro.org>
> submit_for_testing: fix return code error

- testcases/packetdrill.yaml
Adding new networking test case packetdrill.
This will improve test coverage of kernel network sub system.
> testcases: Adding new test case packetdrill

- testcases/kselftests-android.yaml
- testcases/kselftests-drivers.yaml
- testcases/kselftests-short-run-2.yaml
- testcases/kselftests-short-run-3.yaml
- testcases/kselftests-short-run-4.yaml
- testcases/kselftests-short-run-6.yaml
- testcases/kselftests-short-run-7.yaml
- testplans/lkft-kselftest/kselftests-android.yaml
- testplans/lkft-kselftest/kselftests-drivers.yaml
- testplans/lkft-kselftest/kselftests-short-run-6.yaml
- testplans/lkft-kselftest/kselftests-short-run-7.yaml
The overlay size is not enough for more than 7 test definitions
so spliting test cases into small short runs.
> testcases: split kselftests into short runs

- testcases/master/template-kselftest.yaml.jinja2
To make the test_name more readable.
> testcases: master: kselftest: test_name: add a '-'

- projects/lkft/devices/qemu_x86_64
Few test cases expecting the rootfs to have /lib64 so
creating softlink /lib to /lib64.
> devices: qemu_x86_64: Adding softlink from /lib to /lib64

- testplans/lkft-kselftest/kselftests-lkdtm.yaml
lkft-kselftest test plan running lkdtm is creating lot of expected
crash logs. Which is getting hard to find the actual crashes.
so lets not run lkdtm test cases from lkft-kselftest plan.
> testplans: Remove lkdtm test cases from the test plan

- testcases/pmwg.yaml
LAVA testjob submit fail because / returns float and SQUAD/LAVA
expect integer for timeouts.
Set linux-pmwg timeout to test_timeout without division because
{{ test_timeout // 1.5 }} will return float number.
See,
https://qa-reports.linaro.org/testjob/5842098
> testcases/pmwg.yaml: Change timeout division to integer (//)

- devices/qemu_arm64
- devices/qemu_i386
- devices/qemu_x86_64
- qemu.jinja2
This makes it easier to test different qemu version. Just pointing to
another DOCKER_QEMU_VERSION, instead of request the lab to update the
qemu-workers.
> qemu: make it possible to use qemu within a docker container

- projects/lkft/qemu.jinja2
Building up a boot test shows this error:
[            main() ] Failed to parse: /lava-test-plans/tmp/qemu_arm64/boot.yaml
[            main() ] while parsing a block mapping
in "<unicode string>", line 170, column 5:
auto_login:
^ (line: 170)
expected <block end>, but found '-'
in "<unicode string>", line 196, column 5:
- from: inline
^ (line: 196)
Check if 'enable_tests' is defined and set before adding the inline
snippet.
> projects: lkft: qemu: if only boot

- projects/lkft/devices/bcm2711-rpi-4-b
Changing the dtb load addr makes the LKFT kernels to fit.
> lkft: devices: rpi4: increase the boot kernel size

- projects/lkft/devices/juno-r2
Bump the dtb load addr so the KASAN kernel fits.
> lkft: devices: juno-r2: increase the boot kernel size

- projects/lkft/devices/qemu_arm64
Add impdef (Implementation Defined) algorithm is enabled or the
architected QARMA algorithm is enabled. By default the impdef algorithm
is disabled, and QARMA is enabled.
> projects: lkft: devices: qemu_arm64: add TCG impdef

- .github/workflows/test-plans-pipeline.yml
- testcases/vdso.yaml
vdsotest is a utility for testing and benchmarking a Linux VDSO. The
"vDSO" (virtual dynamic shared object) is a small shared library that
the kernel automatically maps into the address space of all user-space
applications.
> testcases: add vdso test

- testplans/lkft-kselftest/kselftests-kvm.yaml
kselftest kvm should not be run on 32-bit architectures and qemu's
so remove it from default test plan and add only to specific device.
> lkft-kselftest: Remove kvm from default kselftest plan

- master.jinja2
fix to only add lxc_xxx_timeout when it's for the lcx_project
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> master.jinja2: fix the calculation of job_timeout

- devices/x15
currently the boot_method is hard coded as u-boot,
there are cases that we could boot the x15 devices
via fastboot as well, hence the change here to make
it possible to override the boot_method when necessary
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> devices/x15: make it possible for other boot_method

- README.md
- fastboot.jinja2
- include/fastboot.jinja2
- master.jinja2
- projects/lkft/fastboot.jinja2
The job_timeout is calculated wrong when running fastboot jobs.
Only caclulate target_deploy_timeout once. Instead of calculate it twice
just split up the fastboot deploy with its own timeout variable
'fastboot_deploy_timeout'. Leave the first target_deploy_timeout as is
even if it does 'to: download' and not 'to: target'
> add a fastboot_deploy_timeout variable

- testcases/master/template-kselftest.yaml.jinja2
The test-name can't contain '.' in it.
error_msg: Invalid job data: ['Invalid characters found in test
definition name: kselftest-net.forwarding', 'Invalid characters found in
test definition name: kselftest-net.mptcp']
Replace '.' with '-' in the name.
> testcases: template: kselftest: no '.' in name field

- testcases/master/template-master.jinja2
With the BUILD_NUMBER in the middle, it's possible to get
the sub job name from the lava job name information.
which would help to check if the lava job is one newly resubmitted.
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
> template-master.jinja2: Put test_name after BUILD_NUMBER for job_name

- projects/lkft/fastboot.jinja2
This will be needed for our kirkstone upgrade where, since we also use multiple test-images
> For kselftest images

- lava_test_plans/devices/juno-r2
- lava_test_plans/devices/x15
- lava_test_plans/devices/x86
Because we are expecting to make an EXT4 file system, the `mkfs.ext4` command has to exist. The `mkfs` helper command, however, may not exist in the DUT root file system.
> devices: juno/x15/x86: Update mkfs -t ext4 -> mkfs.ext4

- submit_for_testing.py
I faced a situation where I had two python3 versions on a docker container, 3.9 on top of /usr/bin and 3.8 on top of /usr/local/bin, on other words
~# ls -la $(which python3)
lrwxrwxrwx 1 root root 9 Aug  2 11:49 /usr/local/bin/python3 -> python3.8
~# ls -la /usr/bin/python3
lrwxrwxrwx 1 root root 9 Apr  5  2021 /usr/bin/python3 -> python3.9
and pip3 using the python 3.8 version. Under this scenario, installing packages through pip3 will not be 'visible' for the submission script which uses python 3.9 , thus letting 'env' decide the python interpreter is the safest approach.
Signed-off-by: Leonardo Sandoval <leonardo.sandoval@linaro.org>
> submit_for_testing: do not hardcode python3 path

- lava_test_plans/testcases/kselftests-arm64.yaml
kselftest arm64 have been added with multiple new test cases due to this the test run time increased to 65 minutes.
> testcases: kselftest: arm64: Increase timeout to 65 minutes

- lava_test_plans/projects/lkft/fastboot.jinja2
Drop passing 'ROOTFS_IMAGE_NAME' to kir's board_setup script.
> projects: lkft: fastboot: drop passing 'ROOTFS_IMAGE_NAME'

- lava_test_plans/testcases/ltp-cve.yaml
Default TIMEOUT_MULTIPLIER is set to 10, That's needed for ltp-cve too.
> testcases: ltp-cve: drop 'TIMEOUT_MULTIPLIER=1'

- lava_test_plans/testcases/kselftests-arm64.yaml
- lava_test_plans/testcases/kselftests-bpf.yaml
- lava_test_plans/testcases/kselftests-drivers.yaml
- lava_test_plans/testcases/kselftests-intel-x86.yaml
- lava_test_plans/testcases/kselftests-kvm.yaml
- lava_test_plans/testcases/kselftests-lkdtm.yaml
- lava_test_plans/testcases/kselftests-net-2.yaml
- lava_test_plans/testcases/kselftests-short-run-1.yaml
- lava_test_plans/testcases/kselftests-short-run-2.yaml
- lava_test_plans/testcases/kselftests-short-run-3.yaml
- lava_test_plans/testcases/kselftests-short-run-4.yaml
- lava_test_plans/testcases/kselftests-short-run-5.yaml
- lava_test_plans/testcases/kselftests-short-run-6.yaml
- lava_test_plans/testcases/kselftests-short-run-7.yaml
A large set of kselftest timedout on emulation platforms due
to short timeout values. This commit is increasing the test run
time values.
> kselftests: Bump kselftests timeout values

- Makefile
Drop parallel builds for now since the following error shows up in the pipeline with that enabled:
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/site-packages/pluggy/_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR> …
> Makefile: drop parallel builds

- .github/workflows/test-plans-pipeline.yml
- Makefile
From this link [1] it looks like installing 'py' will solve the issue.
Link: https://github.com/kevlened/pytest-parallel/issues/118
> Makefile: re-enable parallel tests

- Makefile
The PROJECT variable should be set to lava-test-plans, and the MODULE variable will be set to lava_test_plans.
> Makefile: update the PROJECT name

- .gitlab-ci.yml
Update the build-arg sent in to the containers that will be published to lavasoftware/test-plans.
> gitlab-ci: update the build-arg

- Dockerfile.ci-debian
- Dockerfile.ci-fedora
There is now a schedules pipeline that will rebuild the images weekly.
> Dockerfile.ci-*: drop hardcoded tuxpkg versions

- lava_test_plans/testplans/lkft-full/libhugetlbfs.yaml
Our libhugetlbfs tests fails since there isn't any support in OE [1] since moving from glibc 2.34+.
So lets drop it from the full testplan for LKFT.
Link: https://www.mail-archive.com/openembedded-devel@lists.openembedded.org/msg78304.html
Link: https://github.com/libhugetlbfs/libhugetlbfs/issues/52
> plans: lkft-full: drop libhugetlbfs tests

- lava_test_plans/testcases/kselftests-net.yaml
since upstream selftests net is getting more test cases the LAVA test plans running on LAVA and tuxruns need 30 min more time. This patch is increasing timeout value from 30 to 60 minutes.
> lava_test_plans: kselftests: bump net tests timeout to 60 mins

- lava_test_plans/include/test_target.jinja2
- lava_test_plans/projects/lkft-android/fastboot.jinja2
- lava_test_plans/projects/lkft-android/include/lkft-common-actions.jinja2
- lava_test_plans/projects/lkft-android/variables.ini
to wait for the adb connection ready and to make sure the device is booted up to the home screen, so the real test could do the test directly to avoid such checks.
And the docker method is forced for the lkft-android projects now, as the lxc method is going to be dropped soon.
> lkft-android: add common post boot actions

- lava_test_plans/fastboot.jinja2
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/include/test_target.jinja2
- lava_test_plans/projects/lkft-android/fastboot.jinja2
- lava_test_plans/projects/lkft-android/include/lkft-common-actions.jinja2
- lava_test_plans/projects/lkft-android/variables.ini
- lava_test_plans/projects/lkft/fastboot.jinja2
This PR makes it possible to specify different docker images for deploy and post process, also cleanup the variable for the docker image used for testing.
> Preparation patch for pr-243

- README.md
- test/test_lava_job_visibility.py
- test/variables-visibility-one-group.ini
when there is only one group specified in the variables.ini file, LAVA_JOB_VISIBILITY_GROUPS will be read as
as string, and will not be listed for the visibility items.
This change fixes the problem by adding it as a single lava group for the job visibility item when LAVA_JOB_VISIBILITY_GROUPS is not a sequence.
> master: fix problem when only one group specified

- lava_test_plans/fastboot.jinja2
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/projects/lkft/fastboot.jinja2
- lava_test_plans/projects/lt-qcom/fastboot.jinja2
as there is the case like android that rootfs is not required, but ptable is required
> include:fastboot: drop the rootfs check for ptable partition

- lava_test_plans/projects/lkft-android/fastboot.jinja2
as the lkft-android project needs to have some
secrets set in the lava job for the cts/vts test to upload test results logs to the archive site,
which needs the job to be not public by default,
here set to the "lkft" lava group by default.
> lkft-android: set default group to lkft

- lava_test_plans/devices/hi960-hikey
- lava_test_plans/projects/lkft-android/devices/hi960-hikey
so that it's possible to test the lkft-android jobs with the hikey960 devices.
> lkft-android: add support for the hikey960 device

- lava_test_plans/projects/lkft/devices/dragonboard-410c
Point the default BOOT_URL to the health-check's BOOT_URL that the LAB are using.
> projects: lkft: devices: db410c: add a default BOOT_URL

- lava_test_plans/projects/lkft-android/variables.ini
- lava_test_plans/testcases/android-cts.yaml
- lava_test_plans/testcases/android-vts-kernel-v7a.yaml
- lava_test_plans/testcases/android-vts-kernel-v8a.yaml
- lava_test_plans/testcases/android-vts.yaml
- lava_test_plans/testcases/master/template-android-cts.yaml.jinja2
- lava_test_plans/testcases/master/template-android-vts.yaml.jinja2
- lava_test_plans/testcases/master/template-android-xts.yaml.jinja2
- test/test_lava_test_plans.py
The cts vts  templates added here are generic templates which will be used by many other projects as well
> lkft-android: add cts vts templates for android-mainline projects

- lava_test_plans/projects/lkft-android/devices/dragonboard-845c
- lava_test_plans/projects/lkft-android/devices/hi960-hikey
- lava_test_plans/projects/lkft-android/devices/qrb5165-rb5
dropping  the default or adding default for some variables definition
and fix the syntax for endline of "%}}"
> lkft-android: devices: some improvments from comments for other PR

- lava_test_plans/projects/lkft/fastboot.jinja2
Update the default DOCKER_ROOTFS_FILE to 'rootfs.img' from 'rpb-console-image-lkft.rootfs.img'.
> projects: lkft: fastboot: update default DOCKER_ROOTFS_FILE

- lava_test_plans/testcases/kselftest-short-run-2.yaml
> testcases: kselftest-short-run-2: fix typo filesystems.epoll

- lava_test_plans/include/android-boottime-definition.jinja2
- lava_test_plans/include/boot_target/boot_target.jinja2
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/testcases/android-boottime.yaml
like the job here:
https://lkft.validation.linaro.org/scheduler/job/6601281
> lkft-android: add android boottime testcase

- Dockerfile
Fixes: ec703b5d0b88 ("Dockerfile: update to python:3.11-slim-bookworm")
> Dockerfile: fix container name

- lava_test_plans/testcases/master/template-kselftest.yaml.jinja2
Make the test-name the same as the testcase name, to remove the mismatch in testcases name an test_name.
Reported-by: Senthil Kumaran S <senthil.kumaran@linaro.org>
> testcases: master: template-kselftest: rename test_name

- lava_test_plans/testcases/master/template-kselftest.yaml.jinja2
Default the revision to '.' if TDEFINITIONS_REVISION is not set.
Reported-by: Senthil Kumaran S <senthil.kumaran@linaro.org>
> testcases: master: template-kselftest: set default revision to '.'

- lava_test_plans/testcases/master/template-master.jinja2
Always set systemd's log_level to 'warning', if the user want more logs for debug purpuses then that can be enabled by setting the EXTRA_KERNEL_ARGS='systemd.log_level=debug' and that will override it.
> testcases: template-master: extra_kernel_args: set systemd log_level

- lava_test_plans/testcases/master/template-kselftest.yaml.jinja2
- lava_test_plans/testcases/master/template-network-basic-tests.yaml.jinja2
- lava_test_plans/testcases/master/template-sysbench.yaml.jinja2
- lava_test_plans/testcases/master/template-test.jinja2
- lava_test_plans/testcases/v4l2-compliance.yaml
Change so default in testcases/master/template-test.jinja2 will be so 'test_target_redirect_to_kmsg = true' if nothing else is specified.
any test exept tests inside docker work with redirecting the test output to kmsg.
> Default testcases to use lava signal kmsg

- lava_test_plans/testcases/mmtests-io-fsmark-small-file-stream.yaml
- lava_test_plans/testcases/mmtests-scheduler-schbench.yaml
- lava_test_plans/testcases/mmtests-scheduler-sysbench-thread.yaml
- lava_test_plans/testcases/mmtests-workload-usemem.yaml
New test cases, which use MMTests framework:
- mmtests-io-fsmark-small-file-stream
- mmtests-scheduler-schbench
- mmtests-scheduler-sysbench-thread
- mmtests-workload-usemem
> testcases: additional mmtests

- lava_test_plans/projects/lkft/fastboot.jinja2
Enable docker during the boot section on the fastboot devices. This makes it easier to kill the docker container when a fastboot connection hangs.
> projects: lkft: fastboot: enable docker during boot section

- lava_test_plans/testcases/android-vts-kernel-v7a.yaml
- lava_test_plans/testcases/android-vts-kernel-v8a.yaml
fix the test_name value and testcase file name not the same problem,
and make the xts test suite name overridable for flexibility
> Andorid: changes on test suite name for tuxsuite

- lava_test_plans/projects/lkft-android/include/metadata.jinja2
Default to 'unknown' when a particular metadata parameter is unavailable.
> projects: lkft-android: include: Add defaults to metadata

- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/projects/lkft/devices/dragonboard-845c
Make it possible to download a ramdisk_url, in the db845c case its a initrd that will be used in kir.
the initramfs.cpio.gz file together with the modules creates the initrd.cpio.gz file that makes it possible to load modules that isn't built into the kernel. Which happens when a defconfig kernel are built.
> Fastboot add ramdisk option

- lava_test_plans/fastboot.jinja2
- lava_test_plans/include/boot_target/boot_target.jinja2
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/include/test_target.jinja2
- lava_test_plans/nfs.jinja2
- lava_test_plans/projects/lkft-android/fastboot.jinja2
- lava_test_plans/projects/lkft/devices/e850-96
- lava_test_plans/projects/lkft/devices/qrb5165-rb5
- lava_test_plans/projects/lkft/fastboot.jinja2
This PR will make us help not to pull from docker hub all the time, only when its needed.
The implementation is available in LAVA release 2023.06.
> Docker local true

- lava_test_plans/testcases/templates/kvm-unit-tests.yaml.jinja2
Since rockpi4 has a big.LITTLE hetrogeneous CPU cluster, the kvm-unit-tests suite need to turn off SMP.
> testcases: template: kvm-unit-tests: rockpi4: set SMP to false

- lava_test_plans/projects/lkft/devices/dragonboard-845c
This is a workaround until a proper solution is fixed for why LAVA jobs on db845c ends up with 'Invalid TESTCASE signal'.
Suggested-by: Chase Qi <chase.qi@linaro.org>
> project: lkft: devices: db845c: disable 'lava-signal: kmsg'

- lava_test_plans/projects/lkft/devices/variables/e850-96.yaml
BOOT_URL isn't needed for device e850-96.
> projects: lkft: devices: varibles: e850: drop BOOT_URL

- lava_test_plans/projects/lkft/devices/rk3399-rock-pi-4b
The dtb_addr overwrite the kernel, due to that the kernel has grown to big and overlaps with the dtb.
> projects: lkft: devices: rockpi4: update booti_dtb_addr

- lava_test_plans/testcases/kselftest-net-2.yaml
Drop tc-testing from kselftest-net-2, tc-testing is already in kselftest-short-run-7.
> testcases: kselftest-net-2: drop tc-testing

- lava_test_plans/master.jinja2
LAVA jobs can get stuck for weeks if the priority isn't set properly which makes it pointless running those jobs after a week/month when the artefacts isn't available anymore or when its to late (someone else already done it)to report a bug. Another aspect is that LAVA eat up a lot of time just parsing the queue to find the next job to schedule. By adding a LAVA queue timeout to the job so it gets canceled if not scheduled in time, makes the queue length manageable.
> master: add queue timeout

- lava_test_plans/testcases/templates/kselftest.yaml.jinja2
Prefix the test that stops systemd-timesyncd before kselftest suites are runned.
Reported-by: Benjamin Copeland <benjamin.copeland@linaro.org>
> testcases: templates: kselftest: prefix timesync-off

- lava_test_plans/projects/lkft/fastboot.jinja2
Fixes: 0ac4b2252578 ("projects: lkft: fastboot: kir: use trixie rootfs")
> projects: lkft: devices: fastboot: fix kir update

- lava_test_plans/__main__.py
- lava_test_plans/include/fastboot.jinja2
- lava_test_plans/nfs.jinja2
- lava_test_plans/qemu.jinja2
- lava_test_plans/utils.py
Usage:
```lava-test-plans --device-type x86 --variables ~/work/linaro/notes/lava-bridge/x86-variables-valid.yaml --testplan-device-path devices --dry-run --test-case boot.yaml --overlay https://storage.tuxboot.com/overlays/debian/trixie/amd64/ltp/20240524/ltp.tar.xz /tmp --overlay https://storage.tuxboot.com/overlays/debian/trixie/amd64/ltp/20240524/ltp-1.tar.xz /data --overlay https://storage.tuxboot.com/overlays/debian/trixie/amd64/ltp/20240524/ltp-2.tar.xz /var --overlay https://storage.tuxboot.com/overlays/debian/trixie/amd64/ltp/20240524/ltp-3.tar.xz```
The above should put overlays in the lava job definition at the right place.
> overlays: Implement overlays option
